In [1]:
import numpy as np

In [2]:
6**4

1296

In [3]:
all_dice = []

for i in range(1,7):
    for j in range(1,7):
        for k in range(1,7):
            for l in range(1,7):
                all_dice.append((i,j,k,l))

In [4]:
len(all_dice)

1296

In [5]:
all_dice[:10] #header of first 10 values

[(1, 1, 1, 1),
 (1, 1, 1, 2),
 (1, 1, 1, 3),
 (1, 1, 1, 4),
 (1, 1, 1, 5),
 (1, 1, 1, 6),
 (1, 1, 2, 1),
 (1, 1, 2, 2),
 (1, 1, 2, 3),
 (1, 1, 2, 4)]

In [6]:
from itertools import product

In [7]:
help(product)

Help on class product in module itertools:

class product(builtins.object)
 |  product(*iterables, repeat=1) --> product object
 |
 |  Cartesian product of input iterables.  Equivalent to nested for-loops.
 |
 |  For example, product(A, B) returns the same as:  ((x,y) for x in A for y in B).
 |  The leftmost iterators are in the outermost for-loop, so the output tuples
 |  cycle in a manner similar to an odometer (with the rightmost element changing
 |  on every iteration).
 |
 |  To compute the product of an iterable with itself, specify the number
 |  of repetitions with the optional repeat keyword argument. For example,
 |  product(A, repeat=4) means the same as product(A, A, A, A).
 |
 |  product('ab', range(3)) --> ('a',0) ('a',1) ('a',2) ('b',0) ('b',1) ('b',2)
 |  product((0,1), (0,1), (0,1)) --> (0,0,0) (0,0,1) (0,1,0) (0,1,1) (1,0,0) ...
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Impl

In [8]:
#let's start with repeat=2 just to see what's going on
list(product(range(1,7),repeat=2))   #same as direct or Cartesian product of A x A, from Math 13

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [9]:
temp_list = list(product(range(1,7),repeat=4))

In [10]:
%%time
temp_list = list(product(range(1,7),repeat=20))

MemoryError: 

In [11]:
list(product(["a","b","c"],[5,6])) #cartesian product

[('a', 5), ('a', 6), ('b', 5), ('b', 6), ('c', 5), ('c', 6)]

In [12]:
list(product(["a","b","c"],["a","b","c"],["a","b","c"]))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [13]:
list(product(["a","b","c"],repeat=3))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [14]:
for x in ["a","b","c"]:
    print(x)

a
b
c


In [15]:
len(temp_list)

1296

In [16]:
arr = np.array(temp_list)

In [17]:
arr[:10]

array([[1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 3],
       [1, 1, 1, 4],
       [1, 1, 1, 5],
       [1, 1, 1, 6],
       [1, 1, 2, 1],
       [1, 1, 2, 2],
       [1, 1, 2, 3],
       [1, 1, 2, 4]])

In [18]:
arr.shape

(1296, 4)

In [19]:
#here is our exact probability
(arr.max(axis = 1) == 5).mean()

0.2847222222222222

In [20]:
#Mathematically
(5/6)**4 - (4/6)**4

0.2847222222222223

In [21]:
import numpy as np

In [22]:
rng = np.random.default_rng()

In [23]:
rng.random()

0.6469893860836742

In [24]:
arr = rng.random(size=(100,4))

In [25]:
 arr[:7]  #just first 7 rows (rows 0 through 6), instead of all 100 rows

array([[0.40809255, 0.59949263, 0.13469973, 0.9707137 ],
       [0.63233717, 0.87392637, 0.48916479, 0.41837211],
       [0.34927929, 0.92100313, 0.72206765, 0.91913064],
       [0.22761725, 0.41266244, 0.19297503, 0.01851822],
       [0.27390111, 0.55012183, 0.26517413, 0.95974767],
       [0.47187281, 0.92036099, 0.47083361, 0.39088099],
       [0.31789736, 0.08156143, 0.02635034, 0.74956703]])

In [26]:
arr[:7] > 0.9

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False],
       [False, False, False, False]])

In [27]:
(arr[:7] > 0.9).any()

True

In [28]:
(arr[:7] > 0.9).any(axis=1)

array([ True, False,  True, False,  True,  True, False])

In [29]:
(arr[:7] > 0.9).any(axis=1).sum()

4

In [30]:
arr[:7][(arr[:7] > 0.9).any(axis=1)]

array([[0.40809255, 0.59949263, 0.13469973, 0.9707137 ],
       [0.34927929, 0.92100313, 0.72206765, 0.91913064],
       [0.27390111, 0.55012183, 0.26517413, 0.95974767],
       [0.47187281, 0.92036099, 0.47083361, 0.39088099]])

In [31]:
comparison = arr > 0.9
comp_rows = comparison.any(axis=1)
arr[comp_rows]

#boolean_rows = (arr > 0.9).any(axis=1)
#arr[boolean_rows]

array([[0.40809255, 0.59949263, 0.13469973, 0.9707137 ],
       [0.34927929, 0.92100313, 0.72206765, 0.91913064],
       [0.27390111, 0.55012183, 0.26517413, 0.95974767],
       [0.47187281, 0.92036099, 0.47083361, 0.39088099],
       [0.51459367, 0.01972317, 0.96978356, 0.75495007],
       [0.16354005, 0.96913952, 0.47818394, 0.23162   ],
       [0.56401622, 0.98955673, 0.75282663, 0.74912798],
       [0.73392474, 0.65838303, 0.92377686, 0.69654599],
       [0.2229071 , 0.48273747, 0.66250484, 0.92188398],
       [0.59573085, 0.65220854, 0.99452344, 0.3435752 ],
       [0.66938588, 0.24232147, 0.92643219, 0.76399784],
       [0.99839737, 0.27350901, 0.22046687, 0.73420161],
       [0.13032902, 0.97647631, 0.50442891, 0.86654399],
       [0.33109259, 0.71029416, 0.90529969, 0.30635777],
       [0.48672332, 0.1765958 , 0.34314097, 0.9848034 ],
       [0.41887873, 0.96765958, 0.6073992 , 0.25997894],
       [0.90122997, 0.9589353 , 0.25360602, 0.99930401],
       [0.95287577, 0.63543639,

In [32]:
arr = rng.random(size=(100,4))

In [33]:
arr[:7]

array([[0.69687455, 0.66637386, 0.40509575, 0.00902692],
       [0.24049557, 0.81282625, 0.3803561 , 0.20077933],
       [0.6454469 , 0.7679227 , 0.36510377, 0.2193024 ],
       [0.73151676, 0.75234449, 0.23710365, 0.24034405],
       [0.62791112, 0.45406021, 0.35191859, 0.51591897],
       [0.83809206, 0.84221929, 0.16316119, 0.97632962],
       [0.52850004, 0.8137716 , 0.39239301, 0.49295669]])

In [34]:
((arr[:7] < 0.4)|(arr[:7] > 0.6))

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False]])

In [35]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all()

False

In [36]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)

array([False,  True,  True,  True, False,  True, False])

In [37]:
arr[:7][((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)]

array([[0.24049557, 0.81282625, 0.3803561 , 0.20077933],
       [0.6454469 , 0.7679227 , 0.36510377, 0.2193024 ],
       [0.73151676, 0.75234449, 0.23710365, 0.24034405],
       [0.83809206, 0.84221929, 0.16316119, 0.97632962]])

In [38]:
((arr < 0.4)|(arr > 0.6)).all(axis=1).shape

(100,)

In [39]:
arr[((arr < 0.4)|(arr > 0.6)).all(axis=1)]

array([[0.24049557, 0.81282625, 0.3803561 , 0.20077933],
       [0.6454469 , 0.7679227 , 0.36510377, 0.2193024 ],
       [0.73151676, 0.75234449, 0.23710365, 0.24034405],
       [0.83809206, 0.84221929, 0.16316119, 0.97632962],
       [0.06433286, 0.15550023, 0.23398324, 0.22445107],
       [0.68051389, 0.3893014 , 0.87751241, 0.77829179],
       [0.61543291, 0.25564769, 0.69351164, 0.90795166],
       [0.96547576, 0.90831864, 0.06245619, 0.01243043],
       [0.86702079, 0.69332993, 0.84242448, 0.20939216],
       [0.82301702, 0.81668408, 0.01129489, 0.22697927],
       [0.64376531, 0.97839957, 0.86211016, 0.29382495],
       [0.86749011, 0.90215692, 0.11750232, 0.17789557],
       [0.39259673, 0.99843854, 0.24009075, 0.03395457],
       [0.14887568, 0.69997706, 0.01566433, 0.09854356],
       [0.89914972, 0.70060801, 0.69316381, 0.85517775],
       [0.93415746, 0.08748622, 0.3504843 , 0.23779057],
       [0.89514184, 0.34103432, 0.20722135, 0.85453149],
       [0.15068188, 0.08719298,

In [40]:
arr = rng.integers(2,size=(10,4))

In [41]:
arr

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0]], dtype=int64)

In [42]:
#tuple unpacking
m,n = arr.shape

In [43]:
arr.shape

(10, 4)

In [44]:
m

10

In [45]:
n

4

In [46]:
np.arange(n-1,-1,-1)   #get the exponents first. start at n-1 = 3, stop before -1, and count down -1

array([3, 2, 1, 0])

In [47]:
2**np.arange(n-1,-1,-1)

array([8, 4, 2, 1], dtype=int32)

In [48]:
arr

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0]], dtype=int64)

In [49]:
arr*2**np.arange(n-1,-1,-1)    #Broadcast [8, 4, 2, 1] across all rows of arr, with multiplication

array([[8, 4, 0, 0],
       [8, 4, 2, 0],
       [0, 4, 2, 1],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 2, 0],
       [8, 4, 2, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0],
       [8, 4, 0, 0]], dtype=int64)

In [50]:
(arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

array([12, 14,  7,  4,  2,  2, 14,  2,  0, 12], dtype=int64)

In [51]:
def to_bin(arr):
    _,n = arr.shape   #Note the first part of the shape goes unused, so we can use _ to avoid storing the variable
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [52]:
to_bin(arr)

array([12, 14,  7,  4,  2,  2, 14,  2,  0, 12], dtype=int64)

In [53]:
to_bin(np.array([[1,1],[1,0]]))

array([3, 2])

In [54]:
def to_bin(arr):
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [55]:
arr

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0]], dtype=int64)

In [56]:
type(arr)

numpy.ndarray

In [57]:
isinstance(arr,np.ndarray)

True

In [58]:
isinstance(list(arr),np.ndarray)

False

In [59]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [60]:
to_bin("Hello")

TypeError: Input should be a NumPy array.

In [61]:
to_bin(arr)

array([12, 14,  7,  4,  2,  2, 14,  2,  0, 12], dtype=int64)

In [62]:
to_bin([1,2,3])

TypeError: Input should be a NumPy array.

In [63]:
arr == 0

array([[False, False,  True,  True],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True]])

In [64]:
arr == 1

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [ True,  True,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True,  True, False, False]])

In [65]:
((arr == 0) | (arr == 1))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
#Check if every entry is 0 or 1
((arr == 0) | (arr == 1)).all()

True

In [67]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    if not ((arr == 0) | (arr == 1)).all():
        raise ValueError("All entries should be 0 or 1.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [68]:
arr
arr2 = arr

In [69]:
arr2[5,2] = 6

In [70]:
arr2

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 6, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0]], dtype=int64)

In [71]:
to_bin(arr2)

ValueError: All entries should be 0 or 1.

In [72]:
to_bin(arr)

ValueError: All entries should be 0 or 1.

In [73]:
arr

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 6, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0]], dtype=int64)

In [74]:
arr3 = arr2.copy()

In [75]:
arr3[6,1::2] = 99

In [76]:
arr3

array([[ 1,  1,  0,  0],
       [ 1,  1,  1,  0],
       [ 0,  1,  1,  1],
       [ 0,  1,  0,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  6,  0],
       [ 1, 99,  1, 99],
       [ 0,  0,  1,  0],
       [ 0,  0,  0,  0],
       [ 1,  1,  0,  0]], dtype=int64)

In [77]:
arr2

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 6, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0]], dtype=int64)

In [78]:
mylist = []
for i in range(8):
    mylist.append(7)
mylist

[7, 7, 7, 7, 7, 7, 7, 7]

In [79]:
[7 for _ in range(8)]

[7, 7, 7, 7, 7, 7, 7, 7]

In [80]:
mylist = [-1,4,2,3,-10,2,4]

In [81]:
[x for x in mylist]

[-1, 4, 2, 3, -10, 2, 4]

In [82]:
[x**2 for x in mylist]

[1, 16, 4, 9, 100, 4, 16]

In [83]:
[x for x in mylist if x%2 == 0]

[4, 2, -10, 2, 4]

In [84]:
extralist = []
for x in mylist:
    if x%2 == 0:
        extralist.append(x)
print(extralist)

[4, 2, -10, 2, 4]


In [85]:
mylist

[-1, 4, 2, 3, -10, 2, 4]

In [86]:
[x if x >= 0 else 0 for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [87]:
[0 if x < 0 else x for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [88]:
[[0,1,2] for _ in range(8)]

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

In [89]:
len([[0,1,2] for _ in range(8)])

8

In [90]:
mylist2 = []
for i in range(8):
    for j in range(3):
        mylist2.append(j)
mylist2

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [91]:
len(mylist2)

24

In [92]:
[j for i in range(8) for j in range(3)]

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [93]:
s = '''Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.'''

In [94]:
print(s)

Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.


In [95]:
#Notice this goes character by character
[c for c in s]

['I',
 'n',
 't',
 'r',
 'o',
 'd',
 'u',
 'c',
 't',
 'i',
 'o',
 'n',
 ' ',
 't',
 'o',
 ' ',
 'c',
 'o',
 'm',
 'p',
 'u',
 't',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 'm',
 'i',
 'n',
 'g',
 ' ',
 'u',
 's',
 'i',
 'n',
 'g',
 ' ',
 'M',
 'a',
 't',
 'l',
 'a',
 'b',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '.',
 ' ',
 'R',
 'e',
 'p',
 'r',
 'e',
 's',
 'e',
 'n',
 't',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'o',
 'f',
 ' ',
 'n',
 'u',
 'm',
 'b',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'e',
 'c',
 'i',
 's',
 'i',
 'o',
 'n',
 ',',
 ' ',
 'i',
 'n',
 'p',
 'u',
 't',
 '/',
 'o',
 'u',
 't',
 'p',
 'u',
 't',
 ',',
 ' ',
 'f',
 'u',
 'n',
 'c',
 't',
 'i',
 'o',
 'n',
 's',
 ',',
 ' ',
 'c',
 'u',
 's',
 't',
 'o',
 'm',
 ' ',
 'd',
 'a',
 't',
 'a',
 ' ',
 't',
 'y',
 'p',
 'e',
 's',
 ',',
 ' ',
 't',
 'e',
 's',
 't',
 'i',
 'n',
 'g',
 '/',
 'd',
 'e',
 'b',
 'u',
 'g',
 'g',
 'i'

In [96]:
#This splits the string s at the spaces
wordlist = s.split()
print(wordlist)

['Introduction', 'to', 'computers', 'and', 'programming', 'using', 'Matlab', 'and', 'Python.', 'Representation', 'of', 'numbers', 'and', 'precision,', 'input/output,', 'functions,', 'custom', 'data', 'types,', 'testing/debugging,', 'reading', 'exceptions,', 'plotting', 'data,', 'numerical', 'differentiation,', 'basics', 'of', 'algorithms.', 'Analysis', 'of', 'random', 'processes', 'using', 'computer', 'simulations.']


In [97]:
caplist = [c.capitalize() for c in wordlist]

print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [98]:
caplist = []

for c in wordlist:
    caplist.append(c.capitalize())

In [99]:
print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [100]:
s2 = ' '.join(caplist)

In [101]:
s2

'Introduction To Computers And Programming Using Matlab And Python. Representation Of Numbers And Precision, Input/output, Functions, Custom Data Types, Testing/debugging, Reading Exceptions, Plotting Data, Numerical Differentiation, Basics Of Algorithms. Analysis Of Random Processes Using Computer Simulations.'

In [102]:
type(s2)

str